version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
      - frontend
    environment:
      - DB_HOST=db
  db:
    image: 'mariadb'
    restart: always
    environment:
        MYSQL_DATABASE: foodcare
        MYSQL_ROOT_PASSWORD: root
    volumes:
        - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
        - '1005:80'
    environment:
        - PMA_ARBITRARY=1
  adminer:
    image: adminer
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
volumes:
  db_data:
