version: '3'
services:
  app:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - ../:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - NODE_ENV=development
  db:
    image: 'mariadb'
    restart: always
    environment:
      MYSQL_DATABASE: foodcare
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ../database/dump.sql:/docker-entrypoint-initdb.d/dump.sql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - '1005:80'
    environment:
      - PMA_ARBITRARY=1
volumes:
  db_data: