version: '3'
services:
  db:
    image: mysql:8
    restart: always
    ports:
      - '3308:3306'
    environment:
      - MYSQL_DATABASE=foodcare
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - '1009:80'
    environment:
      - PMA_ARBITRARY=1
  mysql-client:
    image: mysql:8
    command: mysql -h localhost -u root --password=root foodcare
    depends_on:
      - db
    environment:
      - MYSQL_ROOT_PASSWORD=root
volumes:
  db_data:




